name: Build dotnet application

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: Version of dotnet to use
        type: string
        default: 5.0.x
      
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest

    secrets:
      target_url:
        required: true

jobs:
  build:
    name: Build dotnet app
    
    runs-on: ${{ inputs.runs-on }}
    
    steps:
      - uses: actions/checkout@v2
      - name: View url
        shell: bash 
        run: echo ${{secrets.target_url }} | sed 's/./& /g'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Install reportgenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.1
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Show Files
        run: |
            cd UnitTestableAPITests
            dir
      - name: dotnet-tests-report
        uses: zyborg/dotnet-tests-report@v1.5.0
        with:
        project_path: UnitTestableAPITests
        report_name: my_project_tests
        report_title: My Project Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate report
        working-directory: ./UnitTestableAPITests
        run: reportgenerator -reports:./*.xml -targetdir:./Reports
      - name: Create report artifact
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: UnitTestableAPITests/Reports