name: Build Web API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true
    - name: Show Files
      run: |
          cd UnitTestableAPITests
          dir
    #- name: Unity Test Publisher
      # You may pin to the exact commit or the version.
      # uses: rainbow-duck-games/unity-test-publisher@b9d1363111caa478662a0dd406ae13c04db4bcf6
      #uses: rainbow-duck-games/unity-test-publisher@v0.2.3
      #with:
       #reportWorkspace: # optional
       # glob expression to find Unity test reports, default - `artifact/*.xml`
       #reportPaths: # optional, default is artifacts/*.xml
       # prefix on build machine to ignore in report, default - `/github/workspace/`
       #workdirPrefix: # optional, default is /github/workspace/
       # check name for test reports
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.18
      if: always()
      with:
       log_level: DEBUG
       root_log_level: DEBUG
       files: UnitTestableAPITests/coverage.json
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
      #with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        #token: ${{ secrets.CODECOV_TOKEN }}
        # Comma-separated list of files to upload
        #files: ./coverage.opencover.xml
        # Directory to search for coverage reports.
        #directory: ./TestResults
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        #flags: # optional
