name: Build Web API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov 
    - name: Show Files
      run: |
          cd UnitTestableAPITests
          dir
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
        # Comma-separated list of files to upload
        #files: ./coverage.opencover.xml
        # Directory to search for coverage reports.
        directory: ./TestResults
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        #flags: # optional
