name: Build Web API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-dev:
    uses: AmanBedi-msft/DotnetCoreUTAction/.github/workflows/build.yml@main
    with:
      runs-on: ubuntu-latest
      targetenv: dev
    secrets:
      target_url: ${{secrets.SUPER_IMP_URL}}

  build-int:
    uses: AmanBedi-msft/DotnetCoreUTAction/.github/workflows/build.yml@main
    with:
      runs-on: ubuntu-latest
      targetenv: int
    secrets:
      target_url: ${{secrets.SUPER_IMP_URL}}