name: Build Web API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dev:
    environment: # Environment to which the application will be deployed.
      name: dev
    uses: AmanBedi-msft/DotnetCoreUTAction/.github/workflows/build.yml@main
    with:
      runs-on: ubuntu-latest
    secrets:
      target_url: ${{secrets.SUPER_IMP_URL}}

  build-int:
    environment: # Environment to which the application will be deployed.
      name: int
    uses: AmanBedi-msft/DotnetCoreUTAction/.github/workflows/build.yml@main
    with:
      runs-on: ubuntu-latest
    secrets:
      target_url: ${{secrets.SUPER_IMP_URL}}